### ISSUE TITLE
Error during start

### ISSUE THREAD

**Issue by xaenders** [roblanf/minion_qc#29]
Hi,

I tried to rerun MinionQC on a some data I analyzed before. While it worked some months ago, the program now always aborts while it tries to summarize the input file.

I get this output:

$ Rscript MinionQC.R -i input/12h -o output/12h/

Attaching package: ‘scales’

The following object is masked from ‘package:readr’:

    col_factor

The following object is masked from ‘package:viridis’:

    viridis_pal

INFO [2018-02-20 16:20:08]
INFO [2018-02-20 16:20:08] **** Analysing the following files ****
INFO [2018-02-20 16:20:08] input/12h/0/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/1/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/10/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/11/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/2/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/3/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/4/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/5/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/6/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/7/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/8/sequencing_summary.txt
INFO [2018-02-20 16:20:08] input/12h/9/sequencing_summary.txt
INFO [2018-02-20 16:20:08] Loading input file: input/12h/0/sequencing_summary.txt
INFO [2018-02-20 16:20:08] 0: creating output directory:output/12h//0/minionQC
INFO [2018-02-20 16:20:08] 0: summarising input file for flowcell
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
Calls: mclapply ... lapply -> FUN -> single.flowcell -> write -> cat -> file
Execution halted

Could there be something wrong with the files? Or could it have something to do with the masked objects? 
Thank you!
Greetings,
Max

**Comment by roblanf** [comment]
Hmm, not sure at this point. It's not the masked objects, which is normal. Nothing in particular springs to mind though. If you're able to send me this file (e.g. by dropbox link), I could take a look though:

`input/12h/0/sequencing_summary.txt`

The issue is that it can't open the file to write the summary of that flowcell. One thing you could check is that it has successfully created the directory: 

`output/12h//0/minionQC`

If it has, this narrows the problem down to writing the file. If it hasn't then the problem is that it couldn't create this directory for some reason. Either way it would help to know.

**Comment by xaenders** [comment]
Now I could solve it, thank you!
output/12h/0/minionQC was actually not created. 

I did not create output/12h before running the script. If I do that, everything works just fine. Rookie mistake from my side, I guess...

**Comment by roblanf** [comment]
Not a rookie mistake at all! The script should just manage this itself. My guess (I need to check in the script) is that it failed to create the output directory because it was nested two deep. 

I'll leave this issue open until I've fixed it in the script and written a test case so that I can spot it in future. Thanks for posting!

**Comment by roblanf** [comment]
Finally solved here: https://github.com/roblanf/minion_qc/commit/056c45bbefa8267acd5cfbe9b0161c468341cd4b
